border:
  size: 200
  shrink size: 10
  delay: 60
  shrink time: 300

start:
  speed: 60
  tools: false        # Iron sword, axe, pickaxe, stack of blocks
  hunger: true        # Set to false to disable hunger

minimum players: 2
